name: Renovate
on:
  pull_request:
    branches:
      - master
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Bump Helm dependency charts
        run: https://github.com/adusumillipraveen/chart-bump/blob/master/bump-charts.sh