name: Renovate
on:
  pull_request:
    branches:
      - master
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Bump Helm dependency charts
        uses: adusumillipraveen/chart-bump@0.0.3